### ISSUE TITLE
Allow for disabling auto assignment

### ISSUE THREAD

**Issue by develohpanda** [mheap/github-action-issue-management#9]
It would be useful to provide an option to disable the auto-assign functionality of this action. A prime example is this issue: https://github.com/Kong/insomnia/issues/3297, where after some conversation the issue was assigned back to the issue author, but the author is not the one communicating and working through the issue, so the right course of action was to remove the assignment.

With Insomnia open-source we also tend to avoid formally assigning issues and feature requests to contributors (for the time being), so this goes against our repository practices and being able to disable the auto assignment would be awesome.

(If I find some time, I'll raise a PR as well 😃)

**Comment by mheap** [comment]
https://github.com/mheap/github-action-issue-management/releases/tag/v1.1.0 just went out with this functionality. You can set the `disable_auto_assign` input to disable the behaviour
